{
    "id": 1,
    "adminId": 1,
    "jobName": 1,
    "excelId": 1,
    "Exclude": null,
    "IWKSpecialInstruction": null,
    "DCAFiletype": "DR",
    "DCAName": "DR RECOVERIES SDN BHD",
    "DCACode": "DR",
    "State": "JOHOR",
    "Costcode": "1J01840",
    "UO": "UT",
    "LAName": "MAJLIS BANDARAYA ISKANDAR PUTERI",
    "billno": "P2332327",
    "SAN": "82522137",
    "CustomerTelephoneNo": null,
    "CustomerMobileNo": null,
    "CustomerFaxNo": null,
    "CustomerEmail": null,
    "OwnertelNo": null,
    "OwnerMobNo": null,
    "TenantTelNo": "null",
    "TenantMobNo": null,
    "CustomerContactDetail": null,
    "EbillName": null,
    "EbillMobileNo": null,
    "EbillLandlineNo": null,
    "EbillEmail": null,
    "Owner1": "HAJA SALIM BIN E A MOHAMED ISMAIL",
    "Owner2": null,
    "Owner1NRIC": null,
    "Owner2NRIC": null,
    "PropertyStatus": null,
    "PropAddr1": "19 JALAN KELI",
    "PropAddr2": "81300 SKUDAI",
    "PropAddr3": "JOHOR",
    "PropAddr4": null,
    "PropAddr5": null,
    "Building": null,
    "BuildingID": null,
    "Roadname": "JALAN KELI",
    "Taman": null,
    "PostCode": "81300",
    "Suburb": "SKUDAI",
    "MailName1": "HAJA SALIM BIN E A MOHAMED ISMAIL",
    "MailName2": null,
    "MailAdd1": "19 JALAN KELI",
    "MailAdd2": "81300 SKUDAI, JOHOR",
    "MailAdd3": null,
    "MailAdd4": null,
    "Class": "C",
    "Range": "Range5: >120 months",
    "Arrears": "2776.84",
    "CurrentBalance": "0",
    "Balance": "2776.84",
    "BalanceAsPerCopyBill": "2776.84",
    "DiffBetweenBalAsPerCopyBill": null,
    "ICNOs": null,
    "ArrPhone": null,
    "LA_Name": null,
    "LA_New_IC": null,
    "LA_Old_IC": null,
    "LA_Mobile": null,
    "LA_Other_No": null,
    "LA_Email_Add": null,
    "Water_Name": null,
    "Water_New_IC": null,
    "Water_Old_IC": null,
    "Water_Mobile": null,
    "Water_Other_No1": null,
    "Water_Other_No2": null,
    "Water_Email_Add": null,
    "FirstVisitDate": "2022-08-10T00:00:00.000Z",
    "AgentName": "4",
    "updateReminder": null,
    "Occupier": "Vacant",
    "OwnernameCorrect": "yes",
    "specifyCorrectOwnername": "13",
    "OwnerstelNo": null,
    "OwnersMobNo": "null",
    "Ownerfaxno": null,
    "OwnerEmail": "null",
    "TenantName": "14",
    "TenantsTelNo": null,
    "TenantsMobNo": "null",
    "TenantFaxNo": null,
    "TenantEmail": "null",
    "OccupierNationality": "Malaysian",
    "numberOfVisit": 11,
    "Numberoffollowupcalls": "3",
    "PropertyUsage": "23 CAR PARK",
    "PropertyType": "null",
    "NameofShopOrCompany": null,
    "NatureOfBusiness": "15",
    "DRCode": "DR04 UNABLE TO PAY",
    "ReasonCustomerRefuseToPayIWKbill": "null",
    "Remarks": "null",
    "ThirdPartySearch": "null",
    "SourceofTPS": null,
    "TPSOutcomeOrContactNumber": "rushanth",
    "RemarksTPS": "null",
    "AdministrationFee": null,
    "LODFee": null,
    "TotalPayableAmount": null,
    "BATCH": null,
    "Payment": "null",
    "meterImage": null,
    "updateStatus": 0
}