const x = [
    Exclude, 
    Exclude, 
    IWKSpecialInstruction, 
    // DCAFiletype, 
    // DCAName, 
    // DCACode, 
    // State, 
    // Costcode, 
    // UO, 
    // LAName, 
    // billno, 
    // SAN, 
    CustomerTelephoneNo, 
    CustomerMobileNo, 
    CustomerFaxNo, 
    CustomerEmail, 
    OwnertelNo, 
    OwnerMobNo, 
    TenantTelNo, 
    TenantMobNo, 
    CustomerContactDetail, 
    // EbillName, 
    // EbillMobileNo, 
    // EbillLandlineNo, 
    // EbillEmail, 
    // Owner1, 
    // Owner2, 
    // Owner1NRIC, 
    // Owner2NRIC, 
    // PropertyStatus, 
    // PropAddr1, 
    // PropAddr2, 
    // PropAddr3, 
    // PropAddr4, 
    // PropAddr5, 
    Building, 
    BuildingID, 
    // Roadname, 
    // Taman, 
    // PostCode, 
    // Suburb, 
    // MailName1, 
    // MailName2, 
    // MailAdd1, 
    // MailAdd2, 
    // MailAdd3, 
    // MailAdd4, 
    // Class, 
    // Range, 
    // Arrears, 
    // CurrentBalance, 
    // Balance, 
    BalanceAsPerCopyBill, 
    DiffBetweenBalAsPerCopyBill, 
    FirstVisitDate, 
    AgentName, 
    updateReminder, 
    Occupier, 
    OwnernameCorrect, 
    specifyCorrectOwnername, 
    OwnerstelNo, 
    OwnersMobNo, 
    Ownerfaxno, 
    OwnerEmail, 
    TenantName, 
    TenantsTelNo, 
    TenantsMobNo, 
    TenantFaxNo, 
    TenantEmail, 
    OccupierNationality, 
    numberOfVisit, 
    Numberoffollowupcalls, 
    PropertyUsage, 
    PropertyType, 
    NameofShopOrCompany, 
    ReasonCustomerRefuseToPayIWKbill, 
    DRCode, 
    Remarks, 
    ThirdPartySearch, 
    SourceofTPS, 
    TPSOutcomeOrContactNumber, 
    RemarksTPS
]

const stateValues = {{
    "id": 1,
    "adminId": 1,
    "jobName": 1,
    "excelId": 1,
    "DCAFiletype": "DR",
    "DCAName": "PIVOTAL RECOVERIES SDN BHD",
    "DCACode": null,
    "State": "JOHOR",
    "Costcode": "1J01840",
    "UO": "UT",
    "LAName": "MAJLIS BANDARAYA ISKANDAR PUTERI",
    "billno": "X6356185",
    "SAN": "41898081",
    "Owner1": "NEO HOO @ NEW HOW",
    "Owner2": null,
    "Owner1NRIC": null,
    "Owner2NRIC": null,
    "PropAddr1": "4 JALAN TIMOR 12",
    "PropAddr2": "TAMAN TIMOR",
    "PropAddr3": "81300 JOHOR BAHRU",
    "PropAddr4": "JOHOR",
    "Roadname": "JALAN TIMOR 12",
    "Taman": "TAMAN TIMOR",
    "PostCode": "81300",
    "Suburb": "JOHOR BAHRU",
    "MailName1": "NEO HOO @ NEW HOW",
    "MailName2": null,
    "MailAdd1": "4 JALAN TIMOR 12",
    "MailAdd2": "TAMAN TIMOR",
    "MailAdd3": "81300 JOHOR BAHRU",
    "MailAdd4": null,
    "Class": "D",
    "Range": "Range5: >120 months",
    "Arrears": "1226.25",
    "CurrentBalance": "40",
    "Balance_at_05_03_2022": "1266.25",
    "AdministrationFee": "36.6",
    "LODFee": "15",
    "TotalPayableAmount": "1317.85",
    "BATCH": "2022-D-F03-LND-CTOS_PIVOTAL RECOVERIES SDN BHD",
    "Occupier": null,
    "OwnernameCorrect": "Yes",
    "specifyCorrectOwnername": "",
    "OwnertelNo": "",
    "OwnerMobNo": null,
    "OccupierNationality": "",
    "PropertyUsage": "Choose",
    "PropertyType": "Choose",
    "DRCode": "6 DR06 VACANT LAND",
    "Remarks": "",
    "TenantName": "",
    "TenantTelNo": "",
    "Payment": "",
    "status": "",
    "meterImage": null,
    "NatureOfBusiness": null,
    "visitDate": null,
    "updateReminder": null,
    "numberOfVisit": 0,
    "updateStatus": 1,
    "Exclude": null,
    "IWKSpecialInstruction": null,
    "CustomerTelephoneNo": null,
    "CustomerMobileNo": null,
    "CustomerFaxNo": null,
    "CustomerEmail": null,
    "OwnerstelNo": null,
    "OwnersMobNo": null,
    "TenantTelephoneNo": null,
    "TenantMobileNo": null,
    "CustomerContactDetail": null,
    "PropAddr5": null,
    "Building": null,
    "BuildingID": null,
    "AgentName": null,
    "Ownerfaxno": null,
    "OwnerEmail": null,
    "TenantFaxNo": null,
    "TenantEmail": null,
    "Numberoffollowupcalls": null,
    "NameofShopOrCompany": null,
    "ReasonCustomerRefuseToPayIWKbill": null,
    "ThirdPartySearch": null,
    "SourceofTPS": null,
    "TPSOutcomeOrContactNumber": null,
    "RemarksTPS": null
}\